### ISSUE TITLE
About BIM-SLAM

### ISSUE THREAD

**Issue by Yiiboo-w** [MigVega/SLAM2REF#1]
Excellent work! May I kindly ask if the original **BIM-SLAM** code will be released?

**Comment by MigVega** [comment]
Hi @Yiiboo-w ,

No, the BIM-SLAM code will not be released since it's a less mature version of the SLAM2REF code.
Is there something in particular you are interested in from BIM-SLAM?

**Comment by Yiiboo-w** [comment]
> Hi @Yiiboo-w ,
> 
> No, the BIM-SLAM code will not be released since it's a less mature version of the SLAM2REF code. Is there something in particular you are interested in from BIM-SLAM?

Hi @MigVega ,

Yes, I'm curious about the registration performance of the original ICP in BIM-SLAM and YawGICP in SLAM2REF. 
And how do you solve the detection problems of negative differences in the new version?

**Comment by MigVega** [comment]
If I remember right the registration process in BIM SLAM to check for good recognized loops was done with a PLC generalized ICP, as done in the original LT-SLAM.
However that algorithm is unfortunately not as good as Open 3D GICP. I then implemented YawGICP, and I remember it performed better than the previously mentioned algorithms and also than Nano-ICP and than TEASER++.

**Comment by MigVega** [comment]
The difference detection process is done with Octomap and a point to point distance computation, however that part of the method is not open-source.
